# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            On Mapping
tagline:          'Resources on and about mapping with OpenStreetMap'
description:      'Resources on and about mapping with <a href="https://osm.org" target="_blank">OpenStreetMap</a>. Maintained by <a href="https://baato.io" target="_blank">@baato</a>.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Arogya Koirala'
  url:            https://twitter.com/koiralaaa

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/KathmanduLivingLabs/mapping-guide

plugins:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet